# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20160801_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hreference',
            field=models.URLField(max_length=400),
        ),
    ]
