# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20160809_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.City'),
        ),
    ]
